### ISSUE TITLE
wemos mount step/f360 file

### ISSUE THREAD

**Issue by abrugsch** [joranderaaff/portalturret#1]
Thanks for the great project!
Can you provide the step or F360 file for the wemos mount? I have an older D1 mini and I'd like to modify the bracket for the difference in the module that I have (has a discrete 8266 module on the carrier board)

**Comment by joranderaaff** [comment]
Hi! I'll get back to you soon. Was a bit busy. I'll see if I can upload the
files for the WeMos for you.

**Comment by abrugsch** [comment]
Thanks! I have quite a bit of printing still to do so it's not urgent. I will of course contribute the modified version back to the project :)

**Comment by joranderaaff** [comment]
Hi Alistair!

I think I got a STEP file for you of the Wemos mount.. Where do you want me
to send it?
Maybe send your actual email address so I can send it to you?

All the best,

Joran

**Comment by abrugsch** [comment]
You could just add it to the github repo, or in the same place as the rest of the 3D files.

Otherwise my email is the name on my github account, firstname.lastname@gmail

**Comment by AeroX2** [comment]
Hey I'm also really interested in getting access to the CAD files,
I'm looking to make some small modifications and I would really appreciate it!

My email is `james @ snoopyaustralia.com`

Thanks

**Comment by joranderaaff** [comment]
I've added the STEP file to the repo for version 2.0 of the turret.

**Comment by abrugsch** [comment]
Is there much change in V2? I had to re-start my build after most of my printed parts warped in a hot car. I've already picked up the redone wings with added support, has much else changed or just code?

**Comment by joranderaaff** [comment]
There are a few small updates due to change in components. There's significantly less stuff to solder due to a custom PCB and the hole for the PIR sensor got updated to be a bit smaller. But in general you should be able to do most of the stuff with this version.

**Comment by Ev0lve712** [comment]
Good afternoon, I’m currently assembling a turret, when will I have a chance to take a look at v2?

**Comment by joranderaaff** [comment]
The STEP file should be V2. Are there issues with this file for you?

**Comment by Ev0lve712** [comment]
I was a little in a hurry, I have version 4 of Wemos, I can’t figure out where to solder the contacts. D8 is not on this board. 

The remaining contacts also raise questions.

![Wemos D1 mini v4](https://github.com/joranderaaff/portalturret/assets/62849202/1b491ab5-186d-41f7-9ad6-3ed1b93752e7)

**Comment by joranderaaff** [comment]
Please refer to this page to check pin numbering: https://www.wemos.cc/en/latest/d1/d1_mini_3.1.0.html

There's two kinds: **Pin** and **GPIO Pin**. So D8 is the same as GPIO15.

**Comment by Ev0lve712** [comment]
Thanks for the tip, I'll leave this here. Maybe it will be useful to someone.

v3-v4

1-5
2-4
5-14
6-12
7-13
8-15
