### ISSUE TITLE
missing config file ?

### ISSUE THREAD

**Issue by pepouille** [joranderaaff/portalturret#13]
Hi,

I've printed and mostly finished build the 3D object; also ordered some PCB and assembled it. (still missing the accelerometer board, but it is on its way...)

Anyway, I wanted to try the software already, just to hear if some sound for example could be produced.
I'm using a wemos D1 mini clone; I first flashed it with the firmware.bin image you provided.
I couldn't get anything from the speaker, but I could connect to the device's wifi using my phone, and gets redirected to the captive portal, interface was working, but as I didn't have all the servo and so on ready, I couldn't fully test it yet.

I've installed all the building chain and was, after some trick, being able to compile and upload the compiled firmware.
(I'm under linux, not windows; in some of your file, you are including a file with name pins.h, in other it is Pins.h, which is, I suppose, the same file; if under dos/windows, upper/lower-case name doesn't matters apparently, it is not the same under a linux fs. Anyway, I didn't touch the sources files and rather created a symbolic name of Pins.h -> pins.h which did the trick)

I saw the ssid "Portal turret" on my phone, but couldn't connect to it properly this time.

I then open Arduino IDE to have a look at the messages on the serial line; I saw a problem :
"Failed to open settings for reading..."

I've then tried to get the spiffs partition from the device using the "make.sh fs_get"; I modified the script somewhat to avoid it to delete the downloaded fs.bin file; I then extract it in a directory using : 

littlefs-python extract fs.bin fs --block-size=4096

and indeed there were no file in fs.

I've then looked for the same kind of information using your firmware.bin, and with it, I couldn't mount the filesystem (it report a corrupted FS)

Is it normal ?

**Comment by joranderaaff** [comment]
Ah, yes Windows doesn't allow me to change caps, as it will think it's the same file. Rather annoying.

That message about settings is expected. As long as you don't log in to your network OR change something in the settings page, no saving is triggered and it will not create such a settings file. The message is a bit misleading, as the turret should function just fine without that file being there.

If you want to test separate functions, there is a diagnose page that allows you to try hardware, but if you run into issues I strongly advice to create separate small sketches to make sure things work like you would expect.

Not being able to connect the second time is strange though.
