### ISSUE TITLE
Servo WINGS

### ISSUE THREAD

**Issue by Ev0lve712** [joranderaaff/portalturret#3]
Good afternoon, I have a problem with servos. The drive responsible for the wings turns only 5-10 degrees. One way and the other.
What could be the problem?

In the video I used a sketch of an example of "ServoPWM".
https://github.com/joranderaaff/portalturret/assets/62849202/2445906e-4ed4-423f-b45a-8d70ccbdb51a

**Comment by joranderaaff** [comment]
Hi there. I can think of a few things:

- Some servos have slightly different timing when it comes to the PWM signal. These are parameters you can set when initializing the servos. See this page for information on how to tweak: https://www.arduino.cc/reference/en/libraries/servo/attach/
- Is this a regular servo, or did you use a 360 servo by accident? Those two have different characteristics, where "normal" servos are meant to move to a specific angle, and 360 servos move (counter) clockwise depending on the signal you send.

**Comment by Ev0lve712** [comment]
Good day, thank you for the information provided. Indeed, I had both servos with limited angles, I ordered a new one, connected it, it began to rotate endlessly, changed the frequency to “53”, it stopped, according to tests it works well. I'm slowly starting to assemble the turret.
